### ISSUE TITLE
Yorick's pause function causes a crash.

### ISSUE THREAD

**Issue by Clemovski** [dhmunro/pyorick#5]
Since we are here, another problem I had met was the pause function caused an instant crash when called.

```python
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyorick import *
>>> p=Yorick()
>>> p.call.pause(5)
ERROR (VM idle or lost) Segmentation violation interrupt (SIGSEGV)
WARNING aborting on recursive calls to YError
ERROR (VM idle or lost) ym_resume called while not suspended
WARNING aborting on recursive calls to YError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schotte/.local/lib/python3.8/site-packages/pyorick/pyorick.py", line 366, in __call__
    self.bare._reqrep(ID_SUBCALL, self.name, *args, **kwargs)
  File "/home/schotte/.local/lib/python3.8/site-packages/pyorick/pyorick.py", line 232, in _reqrep
    raise PYorickError("yorick sent error reply to request")
pyorick.pyorick.PYorickError: yorick sent error reply to request
```

My workaround is currently to overload the pause function in Yorick to instead call the system sleep function.

```yorick
func pause(time)
// Overloading pause function because it makes pyorick crash.
// Instead of pause we call the system sleep function.
{
    system, swrite(format="sleep %f", time/1000.)
}
```

**Comment by dhmunro** [comment]
Yorick's pause function is extremely complex because it has to be integrated into the
already very complicated event loop.  The only purpose it serves is for interactive X11
movie making, and you should move any such final user output to python as the very
first step in your migration from yorick to python.  (Your fix presumably works for the
special case you are interested in, but has the side effect - which pause does not - of
blocking any other input events, like mouse clicks or motion or keyboard input, which may
arrive during your pause.)  If the pause function works when you run yorick from a
terminal, but is broken when running it from pyorick, then the rather intricate and fragile
additional I/O pipes must somehow be affecting yorick's event loop.  The fact that it
gets a SEGV means there is certainly a bug in yorick itself, presumably on some obscure
branch that it normally does not reach.  If pause never works, you can report a yorick
issue (but that will probably never be fixed - see below).

Note that pyorick is designed so that your yorick program can send code for python
to execute and wait for it to return a result.  Therefore, you could have your overloaded
pause function call a python function which does the pause, rather than starting
a third process to run the sleep command.

Since yorick (as opposed to pyorick) is past its end-of-life, I'm not going to work on this
yorick bug.  Therefore, I'm closing this issue here.  This one is too difficult, and the only
things I can imagine pause being useful for are user interaction features that should be
ported to python very early on.  (Rewriting your workaround to call back python might
be the first step of such a project.)
